### PR TITLE
Shopping cart

### PR DESCRIPTION
**Pull request by jwanggggg**
Features:

- Shopping cart functionality added. Studios and instruments are able to be added to the shopping cart. Cart class is found in cart.js.
- The check out button does not lead to anything yet. Checkout and paypal integration will be added this sprint.
- Date range schema has yet to be added, so the price displayed for rentals is the price per day.

### CODE REVIEW

**Comment by mirahmed39** [comment]
Hey Jonathan,
I have looked at your shopping cart functionality and here
are some things I want to point out or make suggestions:

### Figuring out  Days Rented:

+ user should have an option to delete from their shopping cart as well. In order to accomplish that you can have a delete button attached to each entry and when the user clicks it, it should disappear.

+ The cost does not take into account the number of days chosen for rental period. It only shows the unit cost. You had a question how to calcualte the number of days form the input I created. I have done some research and found a solution.

+ When you choose a date range the you see this format in the input box: ```2019-04-10 to 2019-04-20```. This is simply a string. You can parse out the two dates and use a library called ```moment.js``` to get the number of days between these two dates. I found an example online [moment exmaple](http://jsfiddle.net/wL2f7q0w/). Note that this is done on the front-end. If you want to do it in the backend meaning inside you router function you have to ```npm install moment``` [link to their page](https://www.npmjs.com/package/moment). Now you can require that package inside the .js file that will have your router function and use it to calculate the difference.

### Reason for Instrument and Studio Listing Schema:

+ The reason we have instrument listing schema and studio listing schema is to store the transaction record. Otherwise how would you be able to show a user the list of products he/she ordered?

+ In those two schemas you would see that there is field which stores an array of ```RangeShcema```, which itself has two fields: ```start``` and ```end``` (start date and end date). And the reason I created an array because the product can be booked/rented many times and we need a way to store this info so that in the case anyone chooses to rent the product on those ranges we can let them know.

+ Btw, these are the things I thought about on the beginning of the semester and we might need change it according to our needs (though I think it is still valid). If you think you need to change the design to your needs, please feel free. After all, you are working on this specific feature and you will be able to make better decisions.

**Comment by mirahmed39** [comment]
Nice Job on integrating the changes Jonathan. One quick thing I would like you to fix is when user clicks `rent/purchase` button without selecting a date range. The app crashes if I click rent without choosing date range. You can bypass this check if the user is purchasing the whole thing. Let me know right away once you fix this and I will merge the PR. Well done on the shopping cart!

**Comment by jwanggggg** [comment]
I have added regex checking for the date field.

**Comment by mirahmed39** [comment]
Thanks for adding the check. I have also made a minor change to display a message if user clicks rent without specifying rental period.  I am going to merge the PR. Good Job!

**Pull request merged**
